'use client'

import useSWR from 'swr'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { Search, LocateFixed, Plus, X, Navigation, ShieldCheck, Clock3, Users, Menu, Info, ChevronRight } from 'lucide-react'
import { AddStationSheet } from '@/components/add-station-sheet'
import { stationStatus, statusColor, statusLabel, type FuelType, type Station, type StationStatus, mapsUrl } from '@/lib/stations'
const InteractiveMap = dynamic(() => import('@/components/interactive-map').then((module) => module.InteractiveMap), { ssr: false })

const filters: { label: string; value: 'all' | StationStatus }[] = [{ label: 'Toutes', value: 'all' }, { label: 'Disponibles', value: 'available' }, { label: 'Ruptures', value: 'unavailable' }, { label: 'Incertaines', value: 'uncertain' }, { label: 'Sans info récente', value: 'no_recent_information' }]

function StatusDot({ status }: { status: StationStatus }) { return <span className={`inline-block size-2.5 rounded-full ${statusColor[status]}`} aria-hidden="true" /> }

function StationPanel({ station, onClose, onReport }: { station: Station; onClose: () => void; onReport: () => void }) {
  return <aside className="absolute inset-x-3 bottom-3 z-20 max-w-md overflow-hidden rounded-[1.5rem] border border-white/70 bg-white/95 shadow-2xl backdrop-blur-xl md:inset-x-auto md:left-6 md:w-[390px]">
    <div className="flex items-start justify-between p-5 pb-3"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Station sélectionnée</p><h2 className="text-xl font-bold tracking-tight text-slate-950">{station.name}</h2><p className="mt-1 text-sm text-slate-500">{station.address}, {station.city}</p></div><button onClick={onClose} className="rounded-full p-2 text-slate-400 hover:bg-slate-100" aria-label="Fermer"><X size={18} /></button></div>
    <div className="grid grid-cols-3 gap-2 px-5 py-2">{station.fuels.map((fuel) => <div key={fuel.fuel} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><StatusDot status={fuel.status} />{fuel.fuel}</div><p className="mt-1 text-sm font-bold text-slate-900">{statusLabel[fuel.status]}</p></div>)}</div>
    <div className="flex items-center gap-4 px-5 py-3 text-xs text-slate-500"><span className="flex items-center gap-1"><Clock3 size={14} />{station.updatedAt}</span><span className="flex items-center gap-1"><Users size={14} />{station.confirmations} confirmations</span><span className="flex items-center gap-1"><ShieldCheck size={14} />{station.confidence}%</span></div>
    <div className="flex gap-2 border-t border-slate-100 p-4"><a href={mapsUrl(station)} target="_blank" rel="noreferrer" className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800"><Navigation size={16} />Itinéraire</a><button onClick={onReport} className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-900 hover:bg-slate-50"><Plus size={16} />Mettre à jour</button></div>
  </aside>
}

function ReportSheet({ station, onClose, onSaved }: { station: Station; onClose: () => void; onSaved: (report: { fuel: FuelType; status: StationStatus; reportedAt: string }) => void }) {
  const [fuel, setFuel] = useState<FuelType>('Essence'); const [status, setStatus] = useState<StationStatus>('available'); const [sent, setSent] = useState(false); const [saving, setSaving] = useState(false)
  async function submitReport() { setSaving(true); const response = await fetch('/api/reports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ stationId: station.id, fuel, status }) }); if (response.ok) { const report = await response.json(); onSaved(report); setSent(true) } setSaving(false) }
  if (sent) return <div className="absolute inset-3 z-30 flex items-end justify-center md:items-center"><div className="w-full max-w-md rounded-[1.5rem] bg-white p-7 text-center shadow-2xl"><div className="mx-auto mb-4 flex size-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><ShieldCheck /></div><h2 className="text-xl font-bold text-slate-950">Merci pour la mise à jour</h2><p className="mt-2 text-sm leading-6 text-slate-500">Votre signalement aide les conducteurs du Grand Tunis à prendre une meilleure décision.</p><button onClick={onClose} className="mt-6 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Retour à la carte</button></div></div>
  return <div className="absolute inset-3 z-30 flex items-end justify-center md:items-center"><div className="w-full max-w-md rounded-[1.5rem] bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Signalement rapide</p><h2 className="mt-1 text-xl font-bold text-slate-950">{station.name}</h2></div><button onClick={onClose} aria-label="Fermer" className="rounded-full p-2 text-slate-400 hover:bg-slate-100"><X size={18} /></button></div><p className="mt-5 text-sm font-semibold text-slate-700">Quel carburant ?</p><div className="mt-2 flex gap-2">{(['Essence','Gasoil','Sans plomb'] as FuelType[]).map((item) => <button key={item} onClick={() => setFuel(item)} className={`rounded-full px-3 py-2 text-xs font-semibold ${fuel === item ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{item}</button>)}</div><p className="mt-5 text-sm font-semibold text-slate-700">Disponibilité constatée</p><div className="mt-2 grid grid-cols-3 gap-2">{(['available','unavailable','uncertain'] as StationStatus[]).map((item) => <button key={item} onClick={() => setStatus(item)} className={`flex items-center justify-center gap-2 rounded-xl border px-2 py-3 text-xs font-semibold ${status === item ? 'border-emerald-600 bg-emerald-50 text-emerald-800' : 'border-slate-200 text-slate-600'}`}><StatusDot status={item} />{statusLabel[item]}</button>)}</div><button onClick={submitReport} disabled={saving} className="mt-6 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving ? 'Enregistrement…' : 'Enregistrer la mise à jour'}</button></div></div>
}

const fetcher = (url: string) => fetch(url).then(async (response) => { if (!response.ok) throw new Error('stations fetch failed'); return response.json() })

export function FuelMapApp() {
  const { data: stations = [], error, isLoading, mutate } = useSWR<Station[]>('/api/stations', fetcher)
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | StationStatus>('all'); const [fuel, setFuel] = useState<'all' | FuelType>('all'); const [selected, setSelected] = useState<Station | null>(null); const [reporting, setReporting] = useState(false); const [located, setLocated] = useState(false); const [userLocation, setUserLocation] = useState<[number, number] | null>(null); const [menuOpen, setMenuOpen] = useState(false); const [adding, setAdding] = useState(false)
  const allStations = stations
  const visible = useMemo(() => allStations.filter((station) => { const matchesQuery = `${station.name} ${station.city}`.toLowerCase().includes(query.toLowerCase()); const selectedFuel = fuel === 'all' ? null : station.fuels.find((item) => item.fuel === fuel); const matchesStatus = filter === 'all' || (fuel !== 'all' ? selectedFuel?.status === filter : stationStatus(station) === filter); const matchesFuel = fuel === 'all' || Boolean(selectedFuel); return matchesQuery && matchesStatus && matchesFuel }), [allStations, query, filter, fuel])
  if (isLoading) return <main className="grid min-h-screen place-items-center bg-slate-950 text-white"><p>Chargement des stations…</p></main>
  if (error) return <main className="grid min-h-screen place-items-center bg-slate-950 px-6 text-center text-white"><div><h1 className="text-xl font-bold">Impossible de charger les stations</h1><p className="mt-2 text-sm text-white/70">Vérifiez la connexion à la base de données puis réessayez.</p><button onClick={() => mutate()} className="mt-5 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold">Réessayer</button></div></main>
  return <main className="relative min-h-screen overflow-hidden bg-slate-950 text-slate-900"><header className="absolute inset-x-0 top-0 z-10 flex items-center justify-between px-4 py-4 md:px-6"><Link href="/" className="flex items-center gap-3 rounded-2xl bg-white/95 px-3 py-2 shadow-lg backdrop-blur"><span className="flex size-9 items-center justify-center rounded-xl bg-emerald-600 text-lg font-black text-white">F</span><span><strong className="block text-sm tracking-tight text-slate-950">Fama Carburant</strong><small className="block text-[10px] font-medium text-slate-500">Grand Tunis · en communauté</small></span></Link><nav className="hidden items-center gap-1 rounded-2xl bg-white/95 p-1 shadow-lg md:flex"><Link href="/about" className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">À propos</Link><Link href="/privacy" className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Confidentialité</Link></nav><button type="button" onClick={() => setMenuOpen((open) => !open)} className="rounded-xl bg-white/95 p-3 text-slate-700 shadow-lg md:hidden" aria-label={menuOpen ? 'Fermer le menu' : 'Ouvrir le menu'} aria-expanded={menuOpen}><Menu size={19} /></button>{menuOpen && <nav className="absolute right-4 top-16 flex min-w-44 flex-col gap-1 rounded-2xl bg-white p-2 shadow-xl md:hidden"><Link onClick={() => setMenuOpen(false)} href="/about" className="rounded-xl px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-100">À propos</Link><Link onClick={() => setMenuOpen(false)} href="/privacy" className="rounded-xl px-4 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-100">Confidentialité</Link></nav>}</header>
    <section className="absolute left-3 right-3 top-[88px] z-10 md:left-6 md:top-24 md:w-[450px]"><div className="flex items-center gap-3 rounded-2xl bg-white/95 px-4 py-3 shadow-xl backdrop-blur"><Search size={19} className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher une station ou une ville" className="min-w-0 flex-1 bg-transparent text-sm font-medium text-slate-950 outline-none placeholder:text-slate-400" /></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{filters.map((item) => <button key={item.value} onClick={() => setFilter(item.value)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-bold shadow-sm ${filter === item.value ? 'bg-slate-950 text-white' : 'bg-white/95 text-slate-600'}`}>{item.label}</button>)}</div><div className="mt-2 flex gap-2"><select value={fuel} onChange={(event) => setFuel(event.target.value as 'all' | FuelType)} className="rounded-full border-0 bg-white/95 px-3 py-2 text-xs font-bold text-slate-600 shadow-sm outline-none"><option value="all">Tous les carburants</option><option>Essence</option><option>Gasoil</option><option>Sans plomb</option></select><span className="flex items-center rounded-full bg-white/85 px-3 py-2 text-xs font-semibold text-slate-500">{visible.length} stations visibles</span></div></section>
    <div className="absolute inset-0 bg-slate-200"><div className="absolute bottom-4 left-4 z-10 rounded-xl bg-white/95 px-3 py-2 text-[10px] font-semibold text-slate-600 shadow-lg"><div className="mb-1 font-bold text-slate-900">Disponibilité récente · 2 h</div><div className="flex flex-wrap gap-x-3 gap-y-1"><span className="text-emerald-700">● Disponible</span><span className="text-rose-700">● Indisponible</span><span className="text-amber-700">● Incertain</span><span className="text-slate-500">● Aucune info</span></div></div><InteractiveMap stations={visible} selected={selected} located={located} userLocation={userLocation} onSelect={setSelected} fuelFilter={fuel === 'all' ? undefined : fuel} />{visible.length === 0 && <div className="absolute left-1/2 top-1/2 z-10 -translate-x-1/2 -translate-y-1/2 rounded-2xl bg-white/95 px-5 py-4 text-center shadow-xl"><p className="font-bold text-slate-950">Aucune station trouvée</p><p className="mt-1 text-sm text-slate-500">Essayez un autre carburant ou filtre.</p></div>}</div>
    <div className="absolute bottom-4 right-4 z-10 flex flex-col gap-2 md:bottom-6 md:right-6"><button onClick={() => setAdding(true)} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white shadow-xl hover:bg-emerald-700"><Plus size={17} />Ajouter une station</button><button onClick={() => navigator.geolocation.getCurrentPosition((position) => { setUserLocation([position.coords.latitude, position.coords.longitude]); setLocated(true) }, () => window.alert('La position n’a pas pu être obtenue. Vérifiez l’autorisation de localisation.'))} className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-800 shadow-xl hover:bg-slate-50"><LocateFixed size={17} className={located ? 'text-emerald-600' : ''} />{located ? 'Position trouvée' : 'Me localiser'}</button></div><div className="absolute bottom-5 left-4 z-10 hidden items-center gap-3 rounded-xl bg-slate-950/75 px-4 py-3 text-xs text-white backdrop-blur md:flex"><StatusDot status="available" />Disponible <StatusDot status="unavailable" />Rupture <StatusDot status="uncertain" />Incertain </div>{selected && <StationPanel station={selected} onClose={() => setSelected(null)} onReport={() => setReporting(true)} />}{reporting && selected && <ReportSheet station={selected} onClose={() => { setReporting(false); setSelected(null) }} onSaved={(report) => { const updated = { ...selected, updatedAt: `à l’instant · ${new Date(report.reportedAt).toLocaleString('fr-FR')}`, fuels: selected.fuels.map((item) => item.fuel === report.fuel ? { ...item, status: report.status, updatedAt: `à l’instant · ${new Date(report.reportedAt).toLocaleString('fr-FR')}` } : item), confirmations: selected.confirmations + 1 }; setSelected(updated); mutate() }} />}{adding && <AddStationSheet onClose={() => setAdding(false)} />}<div className="absolute bottom-0 left-0 right-0 z-[5] flex justify-center pb-2 md:bottom-6 md:left-auto md:right-6 md:pb-0"><div className="flex items-center gap-2 rounded-full bg-slate-950/80 px-3 py-2 text-[10px] font-medium text-white/70 backdrop-blur"><Info size={13} />Mis à jour par la communauté</div></div></main>
}
