'use client'

import { useMemo, useState } from 'react'
import Link from 'next/link'
import dynamic from 'next/dynamic'
import { Search, LocateFixed, Plus, X, Navigation, ShieldCheck, Clock3, Users, Menu, Info, ChevronRight } from 'lucide-react'
import { stations, demoStats, stationStatus, statusColor, statusLabel, type FuelType, type Station, type StationStatus, mapsUrl } from '@/lib/stations'
const InteractiveMap = dynamic(() => import('@/components/interactive-map').then((module) => module.InteractiveMap), { ssr: false })

const filters: { label: string; value: 'all' | StationStatus }[] = [{ label: 'Toutes', value: 'all' }, { label: 'Disponibles', value: 'available' }, { label: 'Ruptures', value: 'unavailable' }, { label: 'Incertaines', value: 'uncertain' }]

function StatusDot({ status }: { status: StationStatus }) { return <span className={`inline-block size-2.5 rounded-full ${statusColor[status]}`} aria-hidden="true" /> }

function StationPanel({ station, onClose, onReport }: { station: Station; onClose: () => void; onReport: () => void }) {
  return <aside className="absolute inset-x-3 bottom-3 z-20 max-w-md overflow-hidden rounded-[1.5rem] border border-white/70 bg-white/95 shadow-2xl backdrop-blur-xl md:inset-x-auto md:left-6 md:w-[390px]">
    <div className="flex items-start justify-between p-5 pb-3"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Station sélectionnée</p><h2 className="text-xl font-bold tracking-tight text-slate-950">{station.name}</h2><p className="mt-1 text-sm text-slate-500">{station.address}, {station.city}</p></div><button onClick={onClose} className="rounded-full p-2 text-slate-400 hover:bg-slate-100" aria-label="Fermer"><X size={18} /></button></div>
    <div className="grid grid-cols-3 gap-2 px-5 py-2">{station.fuels.map((fuel) => <div key={fuel.fuel} className="rounded-xl bg-slate-50 p-3"><div className="flex items-center gap-2 text-xs font-medium text-slate-500"><StatusDot status={fuel.status} />{fuel.fuel}</div><p className="mt-1 text-sm font-bold text-slate-900">{statusLabel[fuel.status]}</p></div>)}</div>
    <div className="flex items-center gap-4 px-5 py-3 text-xs text-slate-500"><span className="flex items-center gap-1"><Clock3 size={14} />{station.updatedAt}</span><span className="flex items-center gap-1"><Users size={14} />{station.confirmations} confirmations</span><span className="flex items-center gap-1"><ShieldCheck size={14} />{station.confidence}%</span></div>
    <div className="flex gap-2 border-t border-slate-100 p-4"><a href={mapsUrl(station)} target="_blank" rel="noreferrer" className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white hover:bg-slate-800"><Navigation size={16} />Itinéraire</a><button onClick={onReport} className="flex flex-1 items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-900 hover:bg-slate-50"><Plus size={16} />Mettre à jour</button></div>
  </aside>
}

function ReportSheet({ station, onClose }: { station: Station; onClose: () => void }) {
  const [fuel, setFuel] = useState<FuelType>('Essence'); const [status, setStatus] = useState<StationStatus>('available'); const [sent, setSent] = useState(false)
  if (sent) return <div className="absolute inset-3 z-30 flex items-end justify-center md:items-center"><div className="w-full max-w-md rounded-[1.5rem] bg-white p-7 text-center shadow-2xl"><div className="mx-auto mb-4 flex size-14 items-center justify-center rounded-full bg-emerald-100 text-emerald-700"><ShieldCheck /></div><h2 className="text-xl font-bold text-slate-950">Merci pour la mise à jour</h2><p className="mt-2 text-sm leading-6 text-slate-500">Votre signalement aide les conducteurs du Grand Tunis à prendre une meilleure décision.</p><button onClick={onClose} className="mt-6 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Retour à la carte</button></div></div>
  return <div className="absolute inset-3 z-30 flex items-end justify-center md:items-center"><div className="w-full max-w-md rounded-[1.5rem] bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-700">Signalement rapide</p><h2 className="mt-1 text-xl font-bold text-slate-950">{station.name}</h2></div><button onClick={onClose} aria-label="Fermer" className="rounded-full p-2 text-slate-400 hover:bg-slate-100"><X size={18} /></button></div><p className="mt-5 text-sm font-semibold text-slate-700">Quel carburant ?</p><div className="mt-2 flex gap-2">{(['Essence','Gasoil','Sans plomb'] as FuelType[]).map((item) => <button key={item} onClick={() => setFuel(item)} className={`rounded-full px-3 py-2 text-xs font-semibold ${fuel === item ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{item}</button>)}</div><p className="mt-5 text-sm font-semibold text-slate-700">Disponibilité constatée</p><div className="mt-2 grid grid-cols-3 gap-2">{(['available','unavailable','uncertain'] as StationStatus[]).map((item) => <button key={item} onClick={() => setStatus(item)} className={`flex items-center justify-center gap-2 rounded-xl border px-2 py-3 text-xs font-semibold ${status === item ? 'border-emerald-600 bg-emerald-50 text-emerald-800' : 'border-slate-200 text-slate-600'}`}><StatusDot status={item} />{statusLabel[item]}</button>)}</div><button onClick={() => setSent(true)} className="mt-6 w-full rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white">Envoyer le signalement</button></div></div>
}

export function FuelMapApp() {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState<'all' | StationStatus>('all'); const [fuel, setFuel] = useState<'all' | FuelType>('all'); const [selected, setSelected] = useState<Station | null>(stations[0]); const [reporting, setReporting] = useState(false); const [located, setLocated] = useState(false)
  const visible = useMemo(() => stations.filter((station) => { const matchesQuery = `${station.name} ${station.city}`.toLowerCase().includes(query.toLowerCase()); const matchesStatus = filter === 'all' || stationStatus(station) === filter; const matchesFuel = fuel === 'all' || station.fuels.some((item) => item.fuel === fuel); return matchesQuery && matchesStatus && matchesFuel }), [query, filter, fuel])
  return <main className="relative min-h-screen overflow-hidden bg-slate-950 text-slate-900"><header className="absolute inset-x-0 top-0 z-10 flex items-center justify-between px-4 py-4 md:px-6"><Link href="/" className="flex items-center gap-3 rounded-2xl bg-white/95 px-3 py-2 shadow-lg backdrop-blur"><span className="flex size-9 items-center justify-center rounded-xl bg-emerald-600 text-lg font-black text-white">F</span><span><strong className="block text-sm tracking-tight text-slate-950">Fama Carburant</strong><small className="block text-[10px] font-medium text-slate-500">Grand Tunis · en communauté</small></span></Link><nav className="hidden items-center gap-1 rounded-2xl bg-white/95 p-1 shadow-lg md:flex"><Link href="/about" className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">À propos</Link><Link href="/privacy" className="rounded-xl px-3 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-100">Confidentialité</Link></nav><button className="rounded-xl bg-white/95 p-3 text-slate-700 shadow-lg md:hidden" aria-label="Ouvrir le menu"><Menu size={19} /></button></header>
    <section className="absolute left-3 right-3 top-[88px] z-10 md:left-6 md:top-24 md:w-[450px]"><div className="flex items-center gap-3 rounded-2xl bg-white/95 px-4 py-3 shadow-xl backdrop-blur"><Search size={19} className="text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher une station ou une ville" className="min-w-0 flex-1 bg-transparent text-sm font-medium text-slate-950 outline-none placeholder:text-slate-400" /></div><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{filters.map((item) => <button key={item.value} onClick={() => setFilter(item.value)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-bold shadow-sm ${filter === item.value ? 'bg-slate-950 text-white' : 'bg-white/95 text-slate-600'}`}>{item.label}</button>)}</div><div className="mt-2 flex gap-2"><select value={fuel} onChange={(event) => setFuel(event.target.value as 'all' | FuelType)} className="rounded-full border-0 bg-white/95 px-3 py-2 text-xs font-bold text-slate-600 shadow-sm outline-none"><option value="all">Tous les carburants</option><option>Essence</option><option>Gasoil</option><option>Sans plomb</option></select><span className="flex items-center rounded-full bg-white/85 px-3 py-2 text-xs font-semibold text-slate-500">{visible.length} stations visibles</span></div></section>
    <div className="absolute inset-0 bg-slate-200"><InteractiveMap stations={visible} selected={selected} located={located} onSelect={setSelected} /></div>
    <div className="absolute bottom-4 right-4 z-10 flex flex-col gap-2 md:bottom-6 md:right-6"><button onClick={() => setLocated(true)} className="flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-slate-800 shadow-xl hover:bg-slate-50"><LocateFixed size={17} className={located ? 'text-emerald-600' : ''} />{located ? 'Position trouvée' : 'Me localiser'}</button><Link href="/report" className="flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white shadow-xl hover:bg-emerald-700"><Plus size={17} />Signaler une station</Link></div><div className="absolute bottom-5 left-4 z-10 hidden items-center gap-3 rounded-xl bg-slate-950/75 px-4 py-3 text-xs text-white backdrop-blur md:flex"><StatusDot status="available" />Disponible <StatusDot status="unavailable" />Rupture <StatusDot status="uncertain" />Incertain <span className="ml-2 text-white/60">Données de démonstration</span></div>{selected && <StationPanel station={selected} onClose={() => setSelected(null)} onReport={() => setReporting(true)} />}{reporting && selected && <ReportSheet station={selected} onClose={() => { setReporting(false); setSelected(null) }} />}<div className="absolute bottom-0 left-0 right-0 z-[5] flex justify-center pb-2 md:bottom-6 md:left-auto md:right-6 md:pb-0"><div className="flex items-center gap-2 rounded-full bg-slate-950/80 px-3 py-2 text-[10px] font-medium text-white/70 backdrop-blur"><Info size={13} />Mis à jour par la communauté · {demoStats.reports} contributions</div></div></main>
}
